/**
 * Express Request type augmentation for Pino logging
 * Extends Express Request with pino-http properties
 */

import type { Logger } from 'pino';

declare global {
    namespace Express {
        interface Request {
            /**
             * Request ID for tracing across logs
             * Generated by pino-http middleware
             */
            id: string;

            /**
             * Pino child logger instance scoped to this request
             * Includes requestId in all log entries
             */
            log: Logger;
        }
    }
}
